-- Insert all 60 stimuli with their cue data
INSERT INTO stimuli (image, name, first_letter, category, action, association, features, location, alternatives) VALUES
('1.jpg', 'gloves', 'g', 'clothes', 'These keep you warm', 'coat or scarf', 'This is usually wool or leather', 'You put them on your hands', ARRAY['glove', 'mittens']),
('2.jpg', 'umbrella', 'u', 'rainwear', 'This keeps you dry', 'raincoat or rubbers', 'This collapses', 'you hold it over your head', ARRAY[]),
('3.jpg', 'broom', 'b', 'things that clean', 'This removes dirt from the floor', 'dustpan', 'This has a long handle and bristles', 'This is found in your garage kitchen or basement', ARRAY[]),
('4.jpg', 'shirts', 's', 'clothes', 'you button this', 'pants or sweater', 'This has a collar and cuffs', 'This is worn on your upper body', ARRAY['shirt']),
('5.jpg', 'bathing suit', 'b', 'clothes', 'This is worn in summer', 'swimming pool lake or ocean', 'This can be two piece or one piece', 'This is worn in a pool', ARRAY['swimsuit', 'bikini']),
('6.jpg', 'shorts', 's', 'clothes', 'This is worn in warm weather', 'pants', 'This does not cover the full leg', 'This is worn on the lower part of your body', ARRAY[]),
('7.jpg', 'shoes', 's', 'clothing accessories', 'This helps you walk', 'socks', 'This is usually leather', 'This is worn on your feet', ARRAY['shoe', 'sneakers', 'boots']),
('8.jpg', 'watch', 'w', 'time piece', 'This shows the time', 'clock', 'This has hands and numbers', 'This is worn on your wrist', ARRAY['wristwatch']),
('9.jpg', 'sunglasses', 's', 'clothing accessory', 'This shields your eyes from the sun', 'reading glasses', 'This is plastic and has dark lenses', 'This is worn over your eyes', ARRAY['sun glasses', 'shades']),
('10.jpg', 'guitar', 'g', 'musical instrument', 'This plays songs', 'banjo', 'This has strings', 'This is held over your stomach', ARRAY[]),
('11.jpg', 'ring', 'r', 'clothing accessory', 'This shows that you are married', 'bracelet', 'This is usually silver or gold', 'This is worn on your finger', ARRAY[]),
('12.jpg', 'ties', 't', 'clothing accessory', 'This is used when you dress up', 'collar', 'This is usually silk or cotton', 'This is worn around your neck', ARRAY['tie']),
('13.jpg', 'suitcase', 's', 'travel gear', 'This holds your clothes', 'carry on', 'This has a handle and latches', 'This is used when you travel', ARRAY['luggage', 'bag']),
('14.jpg', 'razor', 'r', 'grooming accessory', 'This removes hair from your face', 'beard', 'This holds a sharp blade', 'This is found in your bathroom', ARRAY[]),
('15.jpg', 'grapefruit', 'g', 'citrus fruit', 'You eat this', 'orange and lemon', 'This is usually sweet', 'This is eaten at breakfast', ARRAY[]),
('16.jpg', 'blueberries', 'b', 'berry', 'You eat this', 'raspberries', 'This is blue', 'This is can be found in a pie', ARRAY['blueberry']),
('17.jpg', 'carrots', 'c', 'vegetable', 'This is good for your eyes', 'rabbits', 'This is orange', 'This is grows in the ground', ARRAY['carrot']),
('18.jpg', 'broccoli', 'b', 'vegetable', 'You eat this', 'cauliflower', 'This is white', 'This is found in the garden', ARRAY[]),
('19.jpg', 'cabbage', 'c', 'vegetable', 'You eat this', 'corned beef', 'This is green', 'This is found in the garden', ARRAY[]),
('20.jpg', 'green beans', 'g', 'vegetable', 'You eat this', 'string beans', 'This has edible pods', 'This is found in the garden', ARRAY['green bean', 'string beans']),
('21.jpg', 'apples', 'a', 'fruit', 'You eat this', 'oranges', 'This can be red green or yellow', 'This grows on a tree', ARRAY['apple']),
('22.jpg', 'radishes', 'r', 'vegetable', 'You eat this', 'salad', 'This is red red', 'This grows in the ground', ARRAY['radish']),
('23.jpg', 'milk', 'm', 'dairy', 'You drink this', 'cream', 'This is white', 'This  comes from a cow', ARRAY[]),
('24.jpg', 'red raspberries', 'r', 'berry', 'You eat this', 'bush with thorns', 'This is red', 'This is grown on a bush', ARRAY['raspberries', 'raspberry']),
('25.jpg', 'green grapes', 'g', 'berry or fruit', 'You eat this', 'wine', 'This is green', 'This is grown on a vine', ARRAY['grapes', 'grape']),
('26.jpg', 'pumpkin', 'p', 'vegetable', 'This is used during Halloween', 'jack-o-lantern', 'This is orange', 'This is grown on a vine', ARRAY[]),
('27.jpg', 'corn', 'c', 'vegetable', 'You eat this', 'maize', 'This has kernels', 'This is grown on a farm', ARRAY[]),
('28.jpg', 'strawberries', 's', 'fruit', 'You eat this', 'and cream', 'This is red', 'This is grown on a small bush or vine', ARRAY['strawberry']),
('29.jpg', 'pizza', 'p', 'food', 'You eat this', 'Italian', 'This has cheese', 'This is baked in an oven', ARRAY[]),
('30.jpg', 'bread', 'b', 'food', 'This rises while it bakes', 'crust', 'This is made from flour', 'This is baked in an oven', ARRAY[]),
('31.jpg', 'lamp', 'l', 'light fixture', 'This provides illumination', 'sun', 'This has a shade', 'This is found on a table', ARRAY[]),
('32.jpg', 'clock', 'c', 'time piece', 'This shows the time', 'wristwatch', 'This has hands and numbers', 'This is found on the wall', ARRAY[]),
('33.jpg', 'almonds', 'a', 'type of nut', 'You eat them', 'almond', 'This is crunchy', 'This is found in your kitchen', ARRAY['almond']),
('34.jpg', 'hanger', 'h', 'closet organizer', 'This holds clothing', 'jacket', 'This is shoulder shaped', 'This is found in the closet', ARRAY['coat hanger', 'clothes hanger']),
('35.jpg', 'cow', 'c', 'animal', 'This provides milk', 'calf', 'This is large', 'This is found on a farm', ARRAY[]),
('36.jpg', 'elephant', 'e', 'animal', 'This does tricks in the zoo', 'tusks', 'This has a trunk', 'This is found in Africa', ARRAY[]),
('37.jpg', 'drinking fountain', 'd', 'a device', 'This provides water', 'thirsty', 'This produces a stream of water', 'This is found in public places', ARRAY['water fountain', 'fountain']),
('38.jpg', 'garage', 'g', 'building', 'This protects automobiles', 'automobile', 'This has a large front door', 'This is attached or near a home', ARRAY[]),
('39.jpg', 'barn', 'b', 'building', 'This is used for storage of grain and hay', 'farm animals', 'This is usually red', 'This is found on a farm', ARRAY[]),
('40.jpg', 'parking meters', 'p', 'device', 'This is where you pay for parking', 'parking lot', 'This has a slot for coins', 'This is found on the street', ARRAY['parking meter', 'meter']),
('41.jpg', 'baseball', 'b', 'sports equipment', 'This is thrown by a pitcher', 'bat', 'This is round with stitches', 'This is found in a baseball game', ARRAY[]),
('42.jpg', 'basketball', 'b', 'sports equipment', 'This is thrown into a hoop', 'hoop', 'This is round', 'This is found in a basketball game', ARRAY[]),
('43.jpg', 'nurse', 'n', 'medical professional', 'She helps sick people', 'doctor', 'She wears a uniform', 'She is found in hospitals', ARRAY[]),
('44.jpg', 'clowns', 'c', 'people', 'They act silly', 'big tent', 'They wear face paint', 'This is found at the circus', ARRAY['clown']),
('45.jpg', 'scissors', 's', 'device', 'This cuts things', 'rock and paper', 'This has two sharp surfaces', 'This is found in a sewing basket', ARRAY[]),
('46.jpg', 'hammer', 'h', 'tool', 'This pounds nails', 'nail', 'This is made of metal', 'This is found in a toolbox', ARRAY[]),
('47.jpg', 'paints', 'p', 'art supplies', 'This changes the color of things', 'brush', 'This is spread with a brush', 'This is found in an art studio', ARRAY['paint']),
('48.jpg', 'ambulance', 'a', 'vehicle', 'This transports sick people', 'hospital', 'This has a flashing red light', 'This is found near hospitals', ARRAY[]),
('49.jpg', 'pineapples', 'p', 'fruit', 'You eat them', 'palm tree', 'This is sweet', 'This is grown high in palm-like trees', ARRAY['pineapple']),
('50.jpg', 'bus', 'b', 'vehicle', 'This transports people', 'trolley', 'This is large', 'This is found on city streets', ARRAY[]),
('51.jpg', 'violin', 'v', 'musical instrument', 'This plays music', 'musician', 'This has a bow and strings', 'This is found in an orchestra', ARRAY[]),
('52.jpg', 'pretzel', 'p', 'food', 'You eat this', 'mustard', 'This is covered with salt', 'This is found in a box or bag', ARRAY[]),
('53.jpg', 'park bench', 'p', 'type of furniture', 'You sit on this', 'park', 'This is made of wood', 'This is found in a park', ARRAY['bench']),
('54.jpg', 'squirrel', 's', 'animal', 'This animal gathers acorns', 'acorns', 'This is usually gray or brown', 'This is found climbing trees', ARRAY[]),
('55.jpg', 'shovel', 's', 'garden tool', 'This digs holes in the ground', 'rake', 'This is made of wood and metal', 'This is used in a garden', ARRAY[]),
('56.jpg', 'telephone', 't', 'communication device', 'This helps you talk to people who are not near you', 'cell phone', 'This has a cord', 'This is found in a home or office', ARRAY['phone', 'telephone']),
('57.jpg', 'garbage truck', 'g', 'vehicle', 'This vehicle hauls trash', 'truck', 'This is large', 'This travels from home to home', ARRAY['trash truck', 'waste truck']),
('58.jpg', 'rolling pin', 'r', 'kitchen utensil', 'This makes dough thin', 'pie crust', 'This is made of wood', 'This is found in the kitchen', ARRAY[]),
('59.jpg', 'screwdriver', 's', 'tool', 'This tool tightens screws', 'screws', 'This is made of metal and has a handle', 'This is found in a toolbox', ARRAY[]),
('60.jpg', 'tennis racket', 't', 'sports equipment', 'This hits balls', 'tennis ball', 'This has nylon or cat gut strings', 'This is found on a tennis court', ARRAY['racket', 'tennis racket']);







